apps/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("add_post", views.add_post, name="add_post"),
    path("post/<str:post_id>", views.show_post, name="post"),
    path("update_post/<str:post_id>", views.update_post, name="update_post"),
    path("delete_post/<str:post_id>", views.delete_post, name="delete_post"),
    path("add_comment/<str:post_id>", views.add_comment, name="add_comment"),
]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("posts.urls")),
    path("user/", include("users.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/posts/models.py
from django.db import models

from users.models import BlogUser


class Post(models.Model):
    """
    OneToMany: user -> post | post -> comment
    """

    id = models.IntegerField(primary_key=True)
    author = models.ForeignKey(to=BlogUser, on_delete=models.CASCADE)
    cover = models.ImageField(
        upload_to="covers/", default="covers/cover-default.png", null=True, blank=True)
    title = models.CharField(max_length=100)
    body = models.TextField(null=True, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    """
    OneToMany: user -> comment | post -> comment
    """

    id = models.IntegerField(primary_key=True)
    author = models.ForeignKey(to=BlogUser, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=False)
    last_modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.body)

apps/posts/forms.py
from django.forms import ModelForm
from django.db.models import ImageField, CharField, TextField

from .models import Post


class PostForm(ModelForm):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        title: CharField = self.fields['title']
        body: TextField = self.fields['body']

        title.widget.attrs.update({'class': 'bg-gray-200 rounded-md p-2 my-4 outline-none text-gray-600 w-full', 'placeholder': '标题'})
        body.widget.attrs.update(
            {'class': 'bg-white rounded-md p-2 my-4 outline-none text-gray-600 border-blue-100 border-2 h-52',
             'cols': '80'})

    class Meta:
        model = Post
        fields = ['title', 'body', ]

apps/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.contrib import messages
from django.core.files.uploadedfile import UploadedFile

from users.models import BlogUser
from .forms import PostForm
from .models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def home(request: HttpRequest):
    post_paginator = Post.objects.all()
    paginator = Paginator(post_paginator, 1)
    page_number = request.GET.get('page', 1)

    try:
        post_list = paginator.page(page_number)

    except PageNotAnInteger:
        post_list = paginator.page(1)

    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)

    if request.user.is_authenticated:
        blog_user = BlogUser.objects.get(user=request.user)
        return render(request, "posts/posts_index.html", {"page_title": "主页", "blog_user": blog_user, "post_list": post_list})

    return render(request, "posts/posts_index.html", {"page_title": "主页", "post_list": post_list})


@login_required(login_url="login")
def add_post(request: HttpRequest):
    blog_user = BlogUser.objects.get(user=request.user)
    form = PostForm()

    if request.method == "POST":
        form = PostForm(request.POST)
        cover: UploadedFile | None = request.FILES.get("cover")

        if form.is_valid() and cover is None:
            post: Post = form.save(commit=False)
            post.author = blog_user
            post.save()
            return redirect("home")
        elif cover is not None:
            post: Post = form.save(commit=False)
            post.author = blog_user
            post.cover.save(cover.name, cover)
            return redirect("home")

    return render(request, "posts/add_post.html", {"page_title": "添加文章", "blog_user": blog_user, "form": form})


def show_post(request: HttpRequest, post_id: str):
    blog_user = None

    if request.user.is_authenticated:  # type: ignore
        blog_user = BlogUser.objects.get(user=request.user)

    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        return redirect("home")

    comments = Comment.objects.filter(post=post)

    body_paragraphs = str(post.body).split("\n")
    return render(
        request, "posts/post.html", {"page_title": post.title, "post": post,
                                     "comments": comments, "body_paragraphs": body_paragraphs, "blog_user": blog_user}
    )


@login_required(login_url="login")
def update_post(request: HttpRequest, post_id: str):
    blog_user = BlogUser.objects.get(user=request.user)

    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        return redirect("home")

    if post.author.id != blog_user.id:
        messages.error(request, "无权修改文章!")
        return redirect("home")

    form = PostForm(instance=post)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        cover: UploadedFile | None = request.FILES.get("cover")
        if form.is_valid() and cover is not None:
            update_form: Post = form.save(commit=False)
            update_form.cover.save(cover.name, cover)
            update_form.save()
            return redirect("home")
        elif form.is_valid():
            form.save()
            return redirect("home")

    return render(request, "posts/update_post.html", {"page_title": "修改文章", "form": form, "post": post, "blog_user": blog_user})


def delete_post(request: HttpRequest, post_id: str):
    blog_user = BlogUser.objects.get(user=request.user)
    try:
        post = Post.objects.get(pk=post_id)
    except Exception:
        return redirect("home")

    if post.author.id != blog_user.id:
        messages.error(request, "无权删除文章!")
        return redirect("home")

    post.delete()
    messages.success(request, "文章删除成功!")

    return redirect("home")


@login_required(login_url="login")
def add_comment(request: HttpRequest, post_id: str):
    blog_user = BlogUser.objects.get(user=request.user)

    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        messages.error(request, "未找到文章")
        return redirect("home")

    if request.method == "POST":
        comment_body = request.POST.get("body")
        if comment_body == None or comment_body == "":
            messages.error(request, "评论无内容")
            return redirect("post", post_id=post_id)

        comment = Comment(author=blog_user, post=post, body=comment_body)
        comment.save()
        messages.success(request, "评论成功!")
        return redirect("post", post_id=post_id)

    body_paragraphs = str(post.body).split("\n")
    return render(request, "posts/post.html", {"page_title": post.title, "post": post, "body_paragraphs": body_paragraphs, "blog_user": blog_user})

apps/posts/templates/posts/add_post.html
{% extends "base.html" %}

{% block content %}

    <form
        class="flex flex-col items-center justify-start p-4 my-8 m-auto bg-gray-50 w-1/2 rounded-md shadow-md"
        action=""
        method="post"
        enctype="multipart/form-data"
        >

            <h3 class="my-2 text-gray-600 text-2xl font-bold">新建文章</h3>

            {% csrf_token %}
            {% for field in form %}
                
                {% if field.label == 'Body' %}
                    
                    <div>
                        <label for="id_body" class="text-gray-600 block">文章内容</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <p class="text-red-400">{{error}}</p>
                        {% endfor %}
                    </div>
                    
                {% else %}
                    <div class="w-1/2">
                        {{ field }}
                        {% for error in field.errors %}
                            <p class="text-red-400">{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                
            {% endfor %}
            
            <div class="mt-4 mb-8 w-1/2">
                <label
                    class="p-2 bg-orange-400 text-white rounded-md hover:bg-orange-300 transition-colors block text-center"
                    for="cover"
                    >文章封面: 选择文件</label
                >
                <input class="hidden" type="file" name="cover" accept="image/*" id="cover" />
            </div>
        
            <input
                type="submit"
                class="bg-blue-400 rounded-md p-2 outline-none text-gray-50 w-1/4 shadow-md transition-transform hover:-translate-y-1 active:translate-y-0 cursor-pointer"
                value="创建文章"
            />
    </form>

{% endblock content %}

apps/posts/templates/posts/post.html
{% extends "base.html" %}

{% block content %}

<section class="bg-gray-100 w-10/12 m-auto my-8 p-4 rounded-md shadow-md">
    <img
        class="w-full rounded-md h-80 object-cover"
        src="{{ post.cover.url }}"
        alt="post cover"
    />

    <h1 class="text-gray-600 font-bold text-center text-3xl my-10">文章标题</h1>

    <div class="flex justify-between items-center bg-blue-100 my-4 mx-20 rounded-md shadow-md p-4">
        <div>
            <p class="text-gray-600">作者: {{ post.author }}</p>
            <p class="text-gray-600">最后一次更新: {{ post.last_modified }}</p>
            <p class="text-gray-600">创建时间: {{ post.created }}</p>
        </div>

        <div>
            {% if request.user.is_authenticated %}
                {% if blog_user.id == post.author.id %}
              <a href="{% url 'update_post' post.id %}" class="text-blue-400 hover:text-blue-300">修改文章</a>
                {% endif %}
            {% endif %}
        </div>
    </div>

    {% for paragraph  in body_paragraphs %}
    <p class="text-gray-500 my-4 mx-20 indent-4">{{ paragraph }}</p>
    {% endfor %}

    
    {% if request.user.is_authenticated %}
        <form class="bg-green-100 my-10 mx-20 p-4 rounded-md shadow-md mt-10" method="post" action="{% url 'add_comment'  post.id %}">
            {% csrf_token %}
            <label for="id_body" class="text-gray-500 block font-bold">你的评论</label>
            <textarea
                class="bg-white rounded-md p-2 my-4 outline-none text-gray-600 border-blue-100 border-2 w-full"
                name="body"
                rows="2"
                id="id_body"
            ></textarea>
            <div class="flex justify-end">
            <input
                type="submit"
                class="bg-blue-400 rounded-md p-2 text-gray-50 w-1/4 shadow-md transition-transform hover:-translate-y-1 active:translate-y-0 cursor-pointer"
                value="评论"
            />
            </div>
        </form>
    {% endif %}
    

    <!-- TODO 待定 | 等待循环 -->
    {% if comments %}
        {% for comment in comments %}
            <div class="bg-blue-100 my-8 mx-20 p-4 rounded-md shadow-md">
                <div class="flex justify-between items-center mx-8">
                    <div>
                        <img
                        class="h-[50px] w-[50px] rounded-full inline-block mr-4 object-cover"
                        src="{{ comment.author.profile_img.url }}"
                        alt="User Profile"
                        />
                        <span class="text-gray-500 text-xl">{{ comment.author.username }}</span>
                    </div>
            
                    <div class="text-gray-400">评论时间: {{ comment.created }}</div>
                </div>
        
                <p class="text-gray-500 mt-4 mx-8">
                    {{ comment.body }}
                </p>
            </div>
        {% endfor %}
    {% endif %}
    

    
    </section>

{% endblock content %}

apps/posts/templates/posts/posts_index.html
{% extends "base.html" %}


{% block content %}

  <main>
    {% for post in post_list %}
      <div class="bg-gray-100 w-7/12 h-60 m-auto my-8 rounded-md shadow-md overflow-hidden flex justify-between">
        <!-- 图片 -->
        <div class="basis-2/6">
          <a href="{% url 'post' post.id %}" class="inline-block">
            <img class="object-cover h-60" src="{{ post.cover.url }}" alt="Cover" />
          </a>
        </div>

        <!-- 内容概览 -->
        <div class="basis-4/6">
          <!-- 标题栏 -->
          <div class="flex justify-between p-4">
            <a href="{% url 'post' post.id %}" class="basis-3/4">
              <h4 class="text-gray-500 font-bold text-xl lg:w-[300px] md:w-[150px] truncate">
                {{ post.title }}
              </h4>
            </a>

            {% if request.user.is_authenticated and blog_user.id == post.author.id%}
            <a href="{% url 'update_post' post.id %}" class="text-blue-400 hover:text-blue-300">修改文章</a>
            {% endif %}

          </div>

          <!-- 文章概要 -->
          <p class="text-gray-400 text-clip inline-block overflow-hidden select-none p-4 h-28">
            {{ post.body }}
          </p>

          <!-- 文章信息 -->
          <div class="flex justify-between p-4">
            <p class="text-gray-600">作者: {{ post.author }}</p>
            <p class="text-gray-400">时间: {{ post.created }}</p>
          </div>
        </div>
      </div>     

    {% endfor %}
  </main>

{% endblock content %}

apps/posts/templates/posts/update_post.html
{% extends "base.html" %}

{% block content %}
    <form
        class="flex flex-col items-center justify-start p-4 my-8 m-auto bg-gray-50 w-1/2 rounded-md shadow-md"
        action=""
        method="post"
        enctype="multipart/form-data"
        >

            <h3 class="my-2 text-gray-600 text-2xl font-bold">修改文章</h3>

            {% csrf_token %}
            {% for field in form %}
            
                {% if field.label == 'Body' %}
                    <div>
                        <label for="id_body" class="text-gray-600 block">文章内容</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <p class="text-red-400">{{error}}</p>
                        {% endfor %}
                    </div>

                {% else %}
                    <div class="w-1/2">
                        {{ field }}
                        {% for error in field.errors %}
                            <p class="text-red-400">{{error}}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                
            {% endfor %}
            
            <div class="mt-4 mb-8 w-1/2">
                <label
                    class="p-2 bg-orange-400 text-white rounded-md hover:bg-orange-300 transition-colors block text-center"
                    for="cover"
                    >文章封面: 选择文件</label
                >
                <input class="hidden" type="file" name="cover" accept="image/*" id="cover" />
            </div>
        
            <div class="w-1/2 my-6 flex justify-around">
                <a
                  href="{% url 'delete_post' post.id %}"
                  class="block text-center bg-red-400 rounded-md p-2 text-gray-50 w-1/4 shadow-md transition-transform hover:-translate-y-1 active:translate-y-0 cursor-pointer"
                  >删除</a
                >
        
                <input
                  type="submit"
                  class="bg-blue-400 rounded-md p-2 text-gray-50 w-1/4 shadow-md transition-transform hover:-translate-y-1 active:translate-y-0 cursor-pointer"
                  value="修改"
                />
              </div>
    </form>


{% endblock content %}