apps/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register', views.register_user, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path("home", views.user_home, name="user_home")
]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("posts.urls")),
    path("user/", include("users.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


class BlogUser(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)

    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    username = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    profile_img = models.ImageField(
        upload_to="profiles/", default="profiles/user-default.png", null=True, blank=True,)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.username

apps/users/forms.py
from typing import Any
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.forms.fields import CharField, EmailField, ImageField

from .models import BlogUser


class BlogUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email",  "password1", "password2"]

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        for _, field in self.fields.items():
            current_field: CharField | EmailField = field
            current_field.widget.attrs.update({'class': 'bg-gray-200 rounded-md p-2 my-4 outline-none text-gray-600 w-full'})

        username: CharField = self.fields['username']
        email: EmailField = self.fields['email']
        password1: CharField = self.fields['password1']
        password2: CharField = self.fields['password2']

        username.widget.attrs.update({'placeholder': '用户名', 'autocomplete': 'bloguser'})
        email.widget.attrs.update({'placeholder': '邮箱', 'autocomplete': 'blogemail'})
        password1.widget.attrs.update({'placeholder': '密码'})
        password2.widget.attrs.update({'placeholder': '确认密码'})


class BlogUserHomeForm(ModelForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            current_field: CharField | EmailField | ImageField = field

            current_field.widget.attrs.update({'class': 'bg-gray-200 rounded-md p-2 my-4 outline-none text-gray-600 w-full'})

    class Meta:
        model = BlogUser
        fields = ['username', 'email']

apps/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, QueryDict
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDict
from django.core.files.uploadedfile import UploadedFile


from .forms import BlogUserCreationForm, BlogUserHomeForm
from .models import BlogUser


def valid_data(post: QueryDict, keys: list) -> bool:
    for key in post:
        if key == "" and key != "csrfmiddlewaretoken":
            return False

        if key not in keys and key != "csrfmiddlewaretoken":
            return False
    return True


def register_user(request: HttpRequest):
    form = BlogUserCreationForm()

    if request.method == "POST":
        form = BlogUserCreationForm(request.POST)
        if form.is_valid():
            user: User = form.save()
            blog_user = BlogUser(
                user=user, username=user.username, email=user.email)
            blog_user.save()
            login(request, user)
            return redirect("home")
        messages.error(request, "Register Failed!")

    if request.user.is_authenticated:
        blog_user = BlogUser.objects.get(user=request.user)
        return redirect("home")

    return render(request, "users/register.html", {"page_title": "注册", "form": form})


def login_user(request: HttpRequest):
    if request.method == "POST":
        if not valid_data(request.POST, ["username", "password"]):
            messages.error(request, "Bad request!")
            return render(request, "users/login.html", {"page_title": "登录"})

        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("home")

        messages.error(request, "Username or Password is wrong!")

    if request.user.is_authenticated:
        return redirect("home")

    return render(request, "users/login.html", {"page_title": "登录"})


def logout_user(request: HttpRequest):
    logout(request)
    return redirect("login")


@login_required(login_url="login")
def user_home(request: HttpRequest):
    user: User = User.objects.get(pk=request.user.pk)
    blog_user = BlogUser.objects.get(user=request.user)
    form = BlogUserHomeForm(instance=blog_user)

    if request.method == "POST":
        profile_img: UploadedFile | None = request.FILES.get("profile_img")

        if profile_img is not None and valid_data(request.POST, ["username", "email", "profile_img"]):
            blog_user.username = user.username = request.POST["username"]
            blog_user.email = user.email = request.POST["email"]
            blog_user.profile_img.save(profile_img.name, profile_img)
            user.save()
            blog_user.save()
            form = BlogUserHomeForm(instance=blog_user)
            messages.success(request, "修改成功!")

        elif valid_data(request.POST, ["username", "email", "profile_img"]):
            blog_user.username = user.username = request.POST["username"]
            blog_user.email = user.email = request.POST["email"]
            user.save()
            blog_user.save()
            form = BlogUserHomeForm(instance=blog_user)
            messages.success(request, "修改成功!")

        blog_user = BlogUser.objects.get(user=request.user)
        form = BlogUserHomeForm(instance=blog_user)

    return render(request, "users/users_home.html", {"form": form, "page_title": "用户主页", "blog_user": blog_user})

apps/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}

<form class="flex flex-col items-center justify-start p-4 mt-14 mb-8 m-auto bg-gray-50 w-1/2 rounded-md shadow-md" action="" method="post">
    {% csrf_token %}
    <h3 class="my-2 text-gray-600 text-2xl font-bold">登录</h3>

    <div class="w-1/2">
        <input type="text" class="bg-gray-200 rounded-md p-2 my-4 outline-none text-gray-600 w-full"
            placeholder="用户名" name="username"/>
    </div>

    <div class="w-1/2">
        <input type="password" class="bg-gray-200 rounded-md p-2 my-4 outline-none text-gray-600 w-full"
            placeholder="密码" name="password"/>
    </div>
    
    <div class="mt-4 mb-8 w-1/2">
        <p class="text-gray-600">没有账号?
            <a href="{% url 'register' %}" class="text-blue-400 font-bold transition-colors hover:text-blue-300">
                注册
            </a>
        </p>
    </div>
    
    <input type="submit"
        class="bg-blue-400 rounded-md p-2 outline-none text-gray-50 w-1/4 shadow-md transition-transform cursor-pointer hover:-translate-y-1 active:translate-y-0"
        value="登录"
    />
</form>

{% endblock content %}

apps/users/templates/users/register.html
{% extends "base.html" %}

{% block content %}

<div>
    <form
        class="flex flex-col items-center justify-start p-4 mt-14 mb-8 m-auto bg-gray-50 w-1/2 rounded-md shadow-md"
        action=""
        method="post"
        >
        {% csrf_token %}
        <h3 class="my-2 text-gray-600 text-2xl font-bold">注 册</h3>
        {% for field in form %}
            <div class="w-1/2">
                {{ field }}
                {% for error in field.errors %}
                    <p class="text-red-400">{{error}}</p>
                {% endfor %}
            </div>
        {% endfor %}

        <div class="mt-4 mb-8 w-1/2">
            <p class="text-gray-600">已有账号?
                <a href="{% url 'login' %}" class="text-blue-400 font-bold transition-colors hover:text-blue-300">
                    登录
                </a>
            </p>
        </div>
        
        <input
            type="submit"
            class="bg-blue-400 rounded-md p-2 outline-none text-gray-50 w-1/4 shadow-md transition-transform hover:-translate-y-1 active:translate-y-0"
            value="注册"
        />
    </form>
</div>

{% endblock content %}

apps/users/templates/users/users_home.html
{% extends "base.html" %}

{% block content %}
    <form
    class="flex flex-col items-center justify-start p-4 my-8 m-auto bg-gray-50 w-1/2 rounded-md shadow-md"
    action=""
    method="post"
    enctype="multipart/form-data"
    >
        <img
        class="h-[100px] w-[100px] rounded-full inline-block mx-4 my-4 object-cover"
        src="{{ blog_user.profile_img.url }}"
        alt="User Profile"
        />

        <h3 class="my-2 text-gray-600 text-2xl font-bold">{{ blog_user.username }}</h3>

        {% csrf_token %}
        {% for field in form %}
            <div class="w-1/2">
                {{ field.label }}
                {{ field }}
                {% for error in field.errors %}
                    <p class="text-red-400">{{error}}</p>
                {% endfor %}
            </div>
        {% endfor %}
        
        {% if request.user.is_authenticated and request.user.is_superuser %}
            <div class="mt-4 mb-8 w-1/2">
                <p class="text-gray-600">你是网站的超级管理员: 
                    <a href="/admin" class="text-blue-400 font-bold transition-colors hover:text-blue-300">
                        前往管理
                    </a>
                </p>
            </div>
        {% endif %}
        
        <div class="mt-4 mb-8 w-1/2">
            <label
            class="p-2 bg-orange-400 text-white rounded-md hover:bg-orange-300 transition-colors block text-center"
            for="id_profile_img"
            >用户头像: 选择文件</label>
            <input
                class="hidden"
                type="file"
                name="profile_img"
                accept="image/*"
                id="id_profile_img"
            />
            </div>

            <input
            type="submit"
            class="bg-blue-400 rounded-md p-2 outline-none text-gray-50 w-1/4 shadow-md transition-transform hover:-translate-y-1 active:translate-y-0 cursor-pointer"
            value="更新"
            />
    </form>
{% endblock content %}